"""
IOLogger: Centralized logging for all LLM interactions.

Captures every input/output for debugging and analysis.
"""
import json
import time
from dataclasses import dataclass, asdict, field
from datetime import datetime
from pathlib import Path
from typing import Optional, Any, Dict
from contextlib import asynccontextmanager


@dataclass
class LLMInteraction:
    """Single LLM call with full input/output capture."""
    timestamp: str
    agent_name: str           # e.g., "SynthesisNetworkAgent", "CriticAgent"
    method_name: str          # e.g., "propose_reaction_with_json_mode"
    step: Optional[int]       # Current workflow step (1-10)
    attempt: Optional[int]    # Current attempt within step (1-5)

    # Full input capture
    system_message: str       # Complete system prompt
    user_message: str         # Complete user prompt

    # Full output capture
    raw_response: str = ""         # Raw LLM response string
    parsed_response: Optional[Dict[str, Any]] = None  # Parsed JSON if applicable
    reasoning: str = ""            # Model reasoning/thinking (e.g., DeepSeek R1 <think> blocks)

    # Metadata
    duration_ms: float = 0.0       # Time taken for LLM call
    success: bool = False          # Whether call succeeded
    error_message: Optional[str] = None  # Error if failed


class IOLogger:
    """
    Thread-safe logger for all LLM interactions.

    Writes to JSON Lines format for easy parsing and streaming.
    Each workflow run gets its own log file.
    """

    def __init__(self, target_molecule: str, output_dir: str = "logs/io"):
        """
        Initialize the I/O logger.

        Args:
            target_molecule: Name of target molecule (used in filename)
            output_dir: Directory for log files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        molecule_name = target_molecule.replace(" ", "_").replace("/", "_")
        self.log_file = self.output_dir / f"{molecule_name}_{timestamp}.jsonl"

        self._current_step: Optional[int] = None
        self._current_attempt: Optional[int] = None

        # Write header comment (not valid JSON, but useful for identification)
        with open(self.log_file, 'w') as f:
            f.write(f"# IOLogger: {target_molecule} - {timestamp}\n")
            f.flush()  # Ensure immediate disk write

    def set_context(self, step: int, attempt: int) -> None:
        """
        Set current step/attempt for subsequent logs.

        Args:
            step: Current workflow step (1-10)
            attempt: Current attempt within step (1-5)
        """
        self._current_step = step
        self._current_attempt = attempt

    def log_interaction(self, interaction: LLMInteraction) -> None:
        """
        Append interaction to JSONL file.

        Args:
            interaction: The LLM interaction to log
        """
        with open(self.log_file, 'a') as f:
            f.write(json.dumps(asdict(interaction), default=str) + '\n')
            f.flush()  # Ensure immediate disk write

    def get_log_path(self) -> str:
        """Return the path to the log file."""
        return str(self.log_file)

    def close(self) -> None:
        """Close the logger (no-op, file writes are immediate)."""
        pass


def log_research_content(
    logger: "IOLogger",
    agent_name: str,
    content: str,
    source_file: Optional[str] = None,
    config_label: Optional[str] = None,
) -> None:
    """Log loaded research content as a special non-LLM entry in the IO log.

    Records cached deep research or MS Discovery content that was loaded
    from files rather than generated by an LLM call, so it appears in
    the JSONL log for this run.
    """
    if logger is None:
        return

    interaction = LLMInteraction(
        timestamp=datetime.now().isoformat(),
        agent_name=agent_name,
        method_name="load_cached_research",
        step=logger._current_step,
        attempt=logger._current_attempt,
        system_message=f"Cached research loaded from: {source_file or 'unknown'}",
        user_message=f"Config: {config_label or 'N/A'}",
        raw_response=content,
        parsed_response={"source": source_file, "config": config_label, "length": len(content)},
        duration_ms=0.0,
        success=True,
        error_message=None,
    )
    logger.log_interaction(interaction)


@asynccontextmanager
async def log_llm_call(
    logger: Optional[IOLogger],
    agent_name: str,
    method_name: str,
    system_message: str,
    user_message: str
):
    """
    Async context manager to log LLM calls with timing.

    Usage:
        async with log_llm_call(logger, "ISMAgent", "propose", sys_msg, user_msg) as interaction:
            response = await client.create(...)
            interaction.raw_response = response.content
            interaction.parsed_response = parsed_data

    Args:
        logger: IOLogger instance (or None to skip logging)
        agent_name: Name of the agent making the call
        method_name: Name of the method being called
        system_message: Complete system prompt
        user_message: Complete user prompt

    Yields:
        LLMInteraction object that caller can populate with response data
    """
    start_time = time.time()

    interaction = LLMInteraction(
        timestamp=datetime.now().isoformat(),
        agent_name=agent_name,
        method_name=method_name,
        step=logger._current_step if logger else None,
        attempt=logger._current_attempt if logger else None,
        system_message=system_message,
        user_message=user_message,
        raw_response="",
        parsed_response=None,
        duration_ms=0.0,
        success=False,
        error_message=None
    )

    try:
        yield interaction
        interaction.success = True
    except Exception as e:
        interaction.error_message = str(e)
        raise
    finally:
        interaction.duration_ms = (time.time() - start_time) * 1000
        if logger:
            logger.log_interaction(interaction)
